# 08/11/2021 01:35 pm - SSN - Copied code. Have to restart products-api and products-db.  Use check_status.ps1.


services:

  products-db:
    image: psdockerrun/products-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=wired
    networks:
      - ps-330-wb-net

  products-api:
    image: psdockerrun/products-api
    ports:
      - "8081:80"
    networks:
      - ps-330-wb-net
    depends_on:
      - products-db

  stock-api:
    image: psdockerrun/stock-api
    ports:
      - "8082:8080"
    networks:
      - ps-330-wb-net
    depends_on:
      - products-db
  
  web:
    image: psdockerrun/web
    ports:
      - "8080:80"
    networks:
      - ps-330-wb-net
    depends_on:
      - products-api      
      - stock-api

  networks:
  ps-330-wb-net: