# 08/15/2021 07:48 am - SSN 
# Replaced psdockerrun/products-db with samniyazi/ps-330-products-db-test-20210815

services:

  products-db-test:
    image: samniyazi/ps-330-products-db-test-20210815
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=wiredtest
    restart: always
    mem_limit: 500M
    networks:
      - ps-330-wb-net

  products-api-test:
    image: psdockerrun/products-api
    ports:
      - "8011:80"
    volumes:
      - ./config/products-api:/app/config
    restart: always
    mem_limit: 500M
    networks:
      - ps-330-wb-net
    depends_on:
      - products-db-test

  stock-api-test:
    image: psdockerrun/stock-api
    ports:
      - "8080" 
    environment:
      - POSTGRES_CONNECTION_STRING=host=products-db-test port=5432 user=postgres password=wiredtest dbname=postgres sslmode=disable
    restart: always
    mem_limit: 125M
    scale: 3
    networks:
      - ps-330-wb-net
    depends_on:
      - products-db-test
  
  web-test:
    image: psdockerrun/web
    ports:
      - "8010:80"
    environment:
      - Environment=Demo3-TEST-2
    volumes:
      - ./config/web/config:/app/config
      - ./config/web/secrets:/app/secrets
    restart: always
    mem_limit: 250M
    networks:
      - ps-330-wb-net
    depends_on:
      - products-api-test
      - stock-api-test

networks:
  ps-330-wb-net: